routes/web.php
<?php
ini_set('max_execution_time', 800000);
ini_set('default_socket_timeout', 600000);

Auth::routes();
Route::get('/', 'DistrictController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('district','DistrictController');
Route::resource('parish','ParishController');
Route::resource('region','RegionController');
Route::resource('sub_county','SubCountyController');
Route::resource('health','HealthAndEducationController');
Route::resource('education','EducationController');
Route::get('test',function(){
	echo phpinfo();
});

resources/views/pages/dashboard.blade.php
@extends('layouts.master')
@section('content')
 
  <h1>{{ $title}}</h1>

<h2>Number of respondents</h2>
 <div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">                      
    <div class="card-box">                   
      <div id="total_best_service_gender" style="height: 400px; margin: 0 auto"></div>
    </div>  
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
      <div class="card-box">                   
        <div id="total_best_service_age" style="height: 400px; margin: 0 auto"></div>
      </div>    
  </div>
</div>



<h2>{{$title_qn_one}}</h2>

<!-- gental best -->
 <div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
        <div class="card-box">                   
            <div id="total_best_service" style="height: 400px; margin: 0 auto"></div>
          
      </div>
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="card-box">                   
            <div id="total_best_service_pie" style="height: 400px; margin: 0 auto"></div>
           
      </div>
  </div>
</div>
<!-- broken best -->


<br><br>
 <div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
           <div class="card-box"> 
           <table class="table" id="Agricultural_Extension_services">
             <thead>
               <th>Service</th> <th>Number of poeple</th>
             </thead>
              <tbody>
               @foreach($total_best_service as $key => $total_best_services)
               <tr>
                 <td>{{ $key}}</td> <td>{{$total_best_services}}</td>
               </tr>
               @endforeach
             </tbody>
           </table>
      
      </div>
  </div>
</div>

<h2>{{$title_qn_two}}</h2>
<h5>The one with a bigger value is the Worst</h5>
 <div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
           <div class="card-box">                   
            <div id="total_worst_service" style="height: 400px; margin: 0 auto"></div>
          </div>
      
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
          <div class="card-box">                    
            <div id="total_worst_service_pie" style="height: 400px; margin: 0 auto"></div>
          </div>
     
  </div>
</div>

<br><br>
 <div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
          <div class="card-box"> 
           <table class="table" id="Agricultural_Extension_services_worst">
             <thead>
               <th>Service</th> <th>Number of poeple</th>
             </thead>
              <tbody>
               @foreach($worst_service as $key => $total_best_services)
               <tr>
                 <td>{{ $key}}</td> <td>{{$total_best_services}}</td>
               </tr>
               @endforeach
             </tbody>
           </table>
        </div>
   
  </div>
</div>

<h2>{{$title_qn_three}}</h2>

<div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
          <div class="card-box">                   
            <div id="total_service_problem" style="height: 400px; margin: 0 auto"></div>
          </div>
     
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
          <div class="card-box">                  
            <div id="total_service_problem_bar" style="height: 400px; margin: 0 auto"></div>
          </div>
     
  </div>
</div>

<br><br>
 <div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="card-box"> 
           <table class="table" id="Agricultural_Extension_services_worst">
             <thead>
               <th>Service</th> <th>Number of poeple</th>
             </thead>
              <tbody>
               @foreach($problem as $key => $total_best_services)
               <tr>
                 <td>{{$key}}</td> <td>{{$total_best_services}}</td>
               </tr>
               @endforeach
             </tbody>
           </table>
        </div>
      </div>
 
</div>


<h2>{{$title_qn_five}}</h2>

<div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
          <div class="card-box">                    
            <div id="total_priority" style="height: 400px; margin: 0 auto"></div>
          </div>
   
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
          <div class="card-box">                    
            <div id="total_priority_bar" style="height: 400px; margin: 0 auto"></div>
          </div>
      
  </div>
</div>

<br><br>
 <div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
          <div class="card-box"> 
           <table class="table" id="Agricultural_Extension_services_worst">
             <thead>
               <th>Service</th> <th>Number of poeple</th>
             </thead>
              <tbody>
               @foreach($priority as $key => $total_best_services)
               <tr>
                 <td>{{$key}}</td> <td>{{$total_best_services}}</td>
               </tr>
               @endforeach
             </tbody>
           </table>
        </div>      
  </div>
</div>


@endsection

@push('scripts')
  <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($problem) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Gender');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Biggest problem facing Agriculture',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.BarChart(document.getElementById('total_service_problem'));
        chart.draw(data, options);        
      }
  </script>

     <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($problem) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Gender');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Biggest problem facing Agriculture',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_service_problem_bar'));
        chart.draw(data, options);        
      }
  </script>

  <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($gender) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Gender');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Sample space by Gender',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_best_service_gender'));
        chart.draw(data, options);        
      }
  </script>

    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($age) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Age range');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Sample space by age range',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_best_service_age'));
        chart.draw(data, options);        
      }
  </script>

 <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($total_best_service) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Agricultural Service');
        data.addColumn('number', 'No. of votes');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Best Agricultural services',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.BarChart(document.getElementById('total_best_service'));
        chart.draw(data, options);        
      }
    </script>

     <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($total_best_service) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Agricultural Service');
        data.addColumn('number', 'No. of votes');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Best Agricultural services',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_best_service_pie'));
        chart.draw(data, options);        
      }
    </script>

    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($worst_service) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Agricultural Service');
        data.addColumn('number', 'No. of votes');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Worst Agricultural services',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.BarChart(document.getElementById('total_worst_service'));
        chart.draw(data, options);        
      }
    </script>

    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($worst_service) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Stages');
        data.addColumn('number', 'No. of votes');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'Worst Agricultural services',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_worst_service_pie'));
        chart.draw(data, options);        
      }
    </script>

    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($priority) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Priority');
        data.addColumn('number', 'No. of votes');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'proposed priorities',
          is3D: true,
          curveType: 'none',
        };        
        var chart1 = new google.visualization.PieChart(document.getElementById('total_priority'));
        chart1.draw(data, options);

        var chart2 = new google.visualization.BarChart(document.getElementById('total_priority_bar'));
        chart2.draw(data, options);
      }
    </script> 
@endpush

resources/views/pages/districts.blade.php
@extends('layouts.master')
@section('content')
<h2>Number of respondents</h2>
 <div class="row"> 
  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">                      
    <div class="card-box">                   
      <div id="total_best_service_gender" style="height: 400px; margin: 0 auto"></div>
    </div>  
  </div>

   <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
      <div class="card-box">                   
        <div id="total_best_service_age" style="height: 400px; margin: 0 auto"></div>
      </div>    
  </div>
</div>

<h1>Distributive data analysis</h1>
<div class="card-box">
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
     @foreach($regions as $region)
      <p class="alert alert-warning"> <a href="{{route('region.show',$region->id)}}">{{$region->name}} Region</a></p>
       @foreach($region->district as $districts)                        
            <p style="margin-left: 30px;"><a href="{{route('district.show',$districts->id)}}"> {{$districts->name}} District </a></p>
            @foreach($districts->subcounty as $sub_country)
              <p style="margin-left: 80px;"><a href="{{route('sub_county.show',$sub_country->id)}}">{{$sub_country->name}} Sub-County</a></p>
             
            @endforeach
        @endforeach
     @endforeach                     
</div>         
@endsection

@push('scripts')
  <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($gender) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Gender');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'All respondents by gender',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_best_service_gender'));
        chart.draw(data, options);        
      }
  </script>

     <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {    
       var record={!! json_encode($category) !!};
       console.log(record);
       // Create our data table.
       var data = new google.visualization.DataTable();
        data.addColumn('string', 'Categories');
        data.addColumn('number', 'No. of poeple');
       for(var k in record){
            var v = record[k];
           
             data.addRow([k,v]);
          console.log(v);
          }
        var options = {
          title: 'All respondents by category',
          is3D: true,
          curveType: 'none',
        };        
        var chart = new google.visualization.PieChart(document.getElementById('total_best_service_age'));
        chart.draw(data, options);        
      }
  </script>

  @endpush

resources/views/pages/education.blade.php
@extends('layouts.master')

@section('content')
<div class="card-box">
  <div class="table-responsive"> 
          <table class="table table-hover" id="Agricultural_Extension_services">
              <thead>
              	<th>#</th>
              	<th>Record id</th>
              	<th>Region</th>
              	<th>District</th>
              	<th>Sub-county</th>
              	<th>Age Category</th>
              	<th>Gender</th>
              	<th>Level of education</th>              	 
              	<th>UPE & USE education</th>
              	<th>Best UPE & USE </th>
              	<th>Best UPE & USE (reason)</th>
              	<th>Worst UPE & USE</th>
              	<th>Worst UPE & USE (Reason)</th>
              	<th>Priority UPE & USE</th>
              	<th>Priority UPE & USE(Reason)</th>

               </thead>

              <tbody>
              	@foreach($health_and_education as $header)
              	<tr>
              		<td>{{$header->id}}</td>		
              		<td>{{$header->record_id}}</td>		
              		<td>{{$header->subcounty->district->region->name}}</td>  
                    <td>{{$header->subcounty->district->name}}</td> 
                    <td>{{$header->subcounty->name}}</td>		
              		<td>{{$header->ageCategory}}</td>		
              		<td>{{$header->gender}}</td>		
              		<td>{{$header->level_of_education}}</td>		
              	 		
              		<td>{{$header->use_education}}</td>		
              		<td>{{$header->best_use_education_service}} {{$header->best_use_education_spec}}</td>		
              		<td>{{$header->best_use_education_reason}}</td>		
              		<td>{{$header->worst_use_education_service}} {{$header->worst_use_education_spec}}</td>		
              		<td>{{$header->worst_use_education_reason}}</td>		
              		<td>{{$header->priority_use_education_service}} {{$header->priority_use_education_spec}}</td>		
              		<td>{{$header->priority_use_education_reason}}</td>               	
              	</tr>
              	@endforeach

              			 
              </tbody>
          </table>
    </div>
</div>
@endsection

resources/views/pages/health_and_education.blade.php
@extends('layouts.master')

@section('content')
<div class="card-box">
  <div class="table-responsive"> 
          <table class="table table-hover" id="Agricultural_Extension_services">
              <thead>
              	<th>#</th>
              	<th>Record id</th>
              	<th>Region</th>
              	<th>District</th>
              	<th>Sub-county</th>
              	<th>Age Category</th>
              	<th>Gender</th>
              	<th>Level of education</th>
              	<th>Health service</th>
              	<th>Health service(Choice)</th>
              	<th>Health service(Reason)</th>
              	<th>Health service(Rate)</th>
              	<th>Health service(Rate reason)</th>
              	<th>Best health Service</th>
              	<th>Best health Service(Reason)</th>
              	<th>Worst health service</th>
              	<th>Worst health service(Reason)</th>
              	<th>Priority health service</th>
              	<th>Priority health service(Reason)</th>
              	 

               </thead>

              <tbody>
              	@foreach($health_and_education as $header)
              	<tr>
              		<td>{{$header->id}}</td>		
              		<td>{{$header->record_id}}</td>		
              		<td>{{$header->subcounty->district->region->name}}</td>  
                    <td>{{$header->subcounty->district->name}}</td> 
                    <td>{{$header->subcounty->name}}</td>		
              		<td>{{$header->ageCategory}}</td>		
              		<td>{{$header->gender}}</td>		
              		<td>{{$header->level_of_education}}</td>		
              		<td>{{$header->establish_health_education}}</td>		
              		<td>{{$header->yes_establish_health_education}}</td>		
              		<td>{{$header->reason_establish_health_education}}</td>		
              		<td>{{$header->rate_establish_health_education}}</td>
              		<td>{{$header->rate_reason_establish_health_education}}</td>		
              		<td>{{$header->best_health_education}} {{$header->best_health_education_spec}}</td>		
              		<td>{{$header->best_health_education_reason}}</td>		
              		<td>{{$header->worst_health_education}}{{$header->worst_health_education_spec}}</td>		
              		<td>{{$header->worst_health_education_reason}}</td>		
              		<td>{{$header->priority_health_education}} {{$header->priority_health_education_spec}}</td>		
              		<td>{{$header->priority_health_education_reason}}</td>		
              		            	
              	</tr>
              	@endforeach

              			 
              </tbody>
          </table>
    </div>
</div>
@endsection